//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uključi editovanje.
        /// </summary>
        public static string Button_EditingOn {
            get {
                return ResourceManager.GetString("Button_EditingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editovanje.
        /// </summary>
        public static string CheckBox_Editing {
            get {
                return ResourceManager.GetString("CheckBox_Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška u parsiranju sadržaja elementa %v1%..
        /// </summary>
        public static string Error_ElementContentParseError {
            get {
                return ResourceManager.GetString("Error_ElementContentParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška u parsiranju elementa %v1% ID-a %v2%..
        /// </summary>
        public static string Error_ElementParseError {
            get {
                return ResourceManager.GetString("Error_ElementParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID %v1% koji je naveden u DataStructure.xml fajlu među poljima za zaglavlje tabele nije ispravan..
        /// </summary>
        public static string Error_TableKeyInvalid {
            get {
                return ResourceManager.GetString("Error_TableKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element %v1% se nalazi van %v2% elementa..
        /// </summary>
        public static string Error_WrongElementPosition {
            get {
                return ResourceManager.GetString("Error_WrongElementPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled pacijenta.
        /// </summary>
        public static string ExternalDataViewItem_Title {
            get {
                return ResourceManager.GetString("ExternalDataViewItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustanak od editovanja.
        /// </summary>
        public static string Message_ChangeLossWarning_Caption {
            get {
                return ResourceManager.GetString("Message_ChangeLossWarning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li zaista želite da odustanete od editovanja?.
        /// </summary>
        public static string Message_ChangeLossWarning_Text {
            get {
                return ResourceManager.GetString("Message_ChangeLossWarning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuspelo čitanje strukture podataka.
        /// </summary>
        public static string Message_CouldNotLoadDataStructure_Caption {
            get {
                return ResourceManager.GetString("Message_CouldNotLoadDataStructure_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struktura podataka nije uspešno učitana..
        /// </summary>
        public static string Message_CouldNotLoadDataStructure_Text {
            get {
                return ResourceManager.GetString("Message_CouldNotLoadDataStructure_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška u parsiranju.
        /// </summary>
        public static string Message_DataStructureParseError_Caption {
            get {
                return ResourceManager.GetString("Message_DataStructureParseError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisanje pacijenata.
        /// </summary>
        public static string Message_DeletionConformation_Caption {
            get {
                return ResourceManager.GetString("Message_DeletionConformation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da obrišete selektovane pacijente? (Ukupan broj selektovanih pacijenata je %v1%).
        /// </summary>
        public static string Message_DeletionConformation_Text {
            get {
                return ResourceManager.GetString("Message_DeletionConformation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuspelo čuvanje fajla.
        /// </summary>
        public static string Message_FileSaveFailed_Caption {
            get {
                return ResourceManager.GetString("Message_FileSaveFailed_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fajl nije uspešno sačuvan. Ukoliko pokušavate da sačuvate fajl preko već postojećeg, proverite da li je postojeći otvoren u nekom drugom programu..
        /// </summary>
        public static string Message_FileSaveFailed_Text {
            get {
                return ResourceManager.GetString("Message_FileSaveFailed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interna greška.
        /// </summary>
        public static string Message_InternalError_Caption {
            get {
                return ResourceManager.GetString("Message_InternalError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogodila se neočekivana greška u radu..
        /// </summary>
        public static string Message_InternalError_Text {
            get {
                return ResourceManager.GetString("Message_InternalError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezna polja nisu popunjena.
        /// </summary>
        public static string Message_MandatoryFieldsNotEdited_Caption {
            get {
                return ResourceManager.GetString("Message_MandatoryFieldsNotEdited_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za svaku sekciju morate označiti da li je editovana ili ne..
        /// </summary>
        public static string Message_MandatoryFieldsNotEdited_Text {
            get {
                return ResourceManager.GetString("Message_MandatoryFieldsNotEdited_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled pacijenata.
        /// </summary>
        public static string Message_OnlyOnePreview_Caption {
            get {
                return ResourceManager.GetString("Message_OnlyOnePreview_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da biste otvorili pregled pacijenta potrebno je da selektujete tačno jedan red u tabeli..
        /// </summary>
        public static string Message_OnlyOnePreview_Text {
            get {
                return ResourceManager.GetString("Message_OnlyOnePreview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi pacijent.
        /// </summary>
        public static string NewEntryWindowTitle {
            get {
                return ResourceManager.GetString("NewEntryWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ne.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje ne sme biti prazno..
        /// </summary>
        public static string Validation_FieldIsEmpty {
            get {
                return ResourceManager.GetString("Validation_FieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dužina unete vrednosti mora biti 13..
        /// </summary>
        public static string Validation_JMBG_InvalidLength {
            get {
                return ResourceManager.GetString("Validation_JMBG_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneta vrednost nije broj..
        /// </summary>
        public static string Validation_NotANumber {
            get {
                return ResourceManager.GetString("Validation_NotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneta vrednost mora biti broj između %v1% i %v2%..
        /// </summary>
        public static string Validation_Range_NumberOutOfBounds {
            get {
                return ResourceManager.GetString("Validation_Range_NumberOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
